### ISSUE TITLE
Using summary statistics only 

### ISSUE THREAD

**Issue by oalavijeh** [xihaoli/MetaSTAAR#3]
Dear MetaSTAAR team, 

Apologies for the basic question but I was wondering if metaSTAAR would work with only summary statistics and no individual level data. I have summary stats from a SAIGE-GENE analysis in two cohort at both a gene and variant level but I do not have access to covariates or individual level patient data. Is there a way to get this to work with metaSTAAR as I all the inputs seem to require a covaraite file? 

Many thanks

**Comment by xihaoli** [comment]
Hi @oalavijeh,

Thanks for your question. MetaSTAAR is designed to work with only summary statistics and no individual-level data. Here, the summary statistics include the covariance (LD) matrices of variants in the given variant set (e.g. a gene or a region), in addition to the variant-level marginal test statistics.

Please feel free to send us [via email](mailto:xihaoli@g.harvard.edu,li@hsph.harvard.edu) if you would like to elaborate more. We can take a closer look and discuss this in more detail.

Best,
Xihao
