### ISSUE TITLE
Is it possible to perform meta-analysis for all variants in a chr?

### ISSUE THREAD

**Issue by pelinunal** [xihaoli/MetaSTAAR#4]
Dear @xihaoli,
I've performed rare variant analysis by using the STAARpipeline for two different datasets. I have agds and obj_nullmodel files for each chromosome for each study.

I would like to perform a meta-analysis of the rare variants with their functional annotation as you provide with this R package. The first step is to create summary statistics and covariance files of each study, the outputs from [MetaSTAAR_worker_sumstat.R](R/MetaSTAAR_worker_sumstat.R) and [MetaSTAAR_worker_cov.R](R/MetaSTAAR_worker_cov.R) .

I would like to use all variants from the agds file chr by chr, instead of a selected variant list.  You can see the code I used below!

```
agds.path <- agds_dir[chr]
genofile <- seqOpen(agds.path)

genotype <- as(as.matrix(readBED(paste0(input_path,"input_10k_chr",chr,"_hg38"), row = 1, col = 1, quiet = TRUE)), "dgCMatrix")

CHR <- as.numeric(seqGetData(genofile, "chromosome"))
position <- as.integer(seqGetData(genofile, "position"))
REF <- as.character(seqGetData(genofile, "$ref"))
ALT <- as.character(seqGetData(genofile, "$alt"))

variant_list <- as.data.frame(cbind.data.frame(CHR,position,REF,ALT))

sumstat <- MetaSTAAR_worker_sumstat(genotype, obj_nullmodel, variant_list, qc_label=NULL)
        
        Error in h(simpleError(msg, call)) : 
        error in evaluating the argument 'x' in selecting a method for function 'colSums': cannot allocate vector of size 17.6 Gb
        In addition: Warning message:
        In asMethod(object) :
        sparse->dense coercion: allocating vector of size 17.6 GiB
```

I wanted to reduce the vector size with a shorter variant list as below, however, it did not work. 
```
n <- 1000
nr <- nrow(variant_list)
splited_data  <- split(variant_list, rep(1:ceiling(nr/n), each=n, length.out=nr))

sumstat_<- c()
for (kk in 1:(nr/n)){

variant_info <- splited_data[[kk]]

sumstat2 <- MetaSTAAR_worker_sumstat(genotype, obj_nullmodel, variant_list, qc_label=NULL)

sumstat <- rbind(sumstat, sumstat2)
}
      Error in MetaSTAAR_worker_sumstat(genotype, obj_nullmodel, variant_info,  : 
      Dimensions don't match for genotype and variant_info!
      In addition: Warning message:
      In asMethod(object) :
      sparse->dense coercion: allocating vector of size 17.6 GiB
```

Is it possible to perform for all variants in the chr? Do you have any suggestions to reduce the vector size?
Thank you!
Bests,
Pelin

**Comment by xihaoli** [comment]
Hi @pelinunal,

Thanks for your question. Yes, MetaSTAAR is developed to perform meta-analysis of rare variants with their functional annotations, and the first step is to create summary statistics and covariance files of each study using MetaSTAARWorker. MetaSTAAR is designed to store and share all variants in the chromosome, instead of a selected variant list, to allow for post hoc definitions of variant sets. In practice, the whole chromosome genotype files are sliced into sufficiently long segments to facilitate parallel computing.

For more details, please [email](mailto:xihaoli@unc.edu) to better assist your use case.

Best,
Xihao

**Comment by pelinunal** [comment]
Thank you @xihaoli!
I will contact you via email. 

Bests,
Pelin
